In [132]:
import numpy as np

In [134]:
a = np.arange(2,15)

In [136]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [138]:
a[0]

2

In [140]:
a[1:2]

array([3])

In [142]:
a[-1]

14

In [144]:
b = np.identity(8)

In [146]:
b

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [148]:
b[0]

array([1., 0., 0., 0., 0., 0., 0., 0.])

In [150]:
b[2]

array([0., 0., 1., 0., 0., 0., 0., 0.])

In [152]:
b[0::2,2]

array([0., 1., 0., 0.])

In [154]:
b[2:5,2:5]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
b[2:5]

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

In [158]:
b[2:5, 4]

array([0., 0., 1.])

In [160]:
a = np.arange(1,50).reshape(7,7)

In [162]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [164]:
a[1:3,1:3]

array([[ 9, 10],
       [16, 17]])

In [166]:
a[3]

array([22, 23, 24, 25, 26, 27, 28])

In [168]:
b = [True, True, False, True, False]

In [170]:
a[b]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 5

In [172]:
b = [True, True, False, True]

In [174]:
a[b]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 4

In [176]:
# create an array of row 5 and column 5 and fill with 8

In [178]:
c = np.full((5,5), 8)

In [180]:
c

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [182]:
c[1:4, 1:4]

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [184]:
a = np.arange(2,10)

In [186]:
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
a +2

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [190]:
a ** 2

array([ 4,  9, 16, 25, 36, 49, 64, 81])

In [192]:
salary = np.array([25000, 34000, 12000, 45000])

In [194]:
salary

array([25000, 34000, 12000, 45000])

In [196]:
salary - 5000

array([20000, 29000,  7000, 40000])

In [198]:
a = np.array([1,2,3,4,5])

In [200]:
b = np.array([3,4,5,6,7])

In [202]:
a

array([1, 2, 3, 4, 5])

In [204]:
b

array([3, 4, 5, 6, 7])

In [206]:
a+b

array([ 4,  6,  8, 10, 12])

In [208]:
c = np.array([1,2,3])

In [210]:
c

array([1, 2, 3])

In [212]:
a+c

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [214]:
a

array([1, 2, 3, 4, 5])

In [216]:
a > 3
a % 2 == 0

array([False,  True, False,  True, False])

In [218]:
a >3

array([False, False, False,  True,  True])

In [220]:
a % 2 == 0

array([False,  True, False,  True, False])

In [222]:
a = np.arange(5,15)

In [224]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [226]:
(a%2==0) & (a>8)

array([False, False, False, False, False,  True, False,  True, False,
        True])

In [228]:
b = (a%2 == 0) & (a > 8)

In [230]:
b

array([False, False, False, False, False,  True, False,  True, False,
        True])

In [232]:
a[b]

array([10, 12, 14])

In [234]:
a = np.arange(8)

In [236]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [238]:
a %2==0

array([ True, False,  True, False,  True, False,  True, False])

In [240]:
a[a%2==0]

array([0, 2, 4, 6])

In [242]:
a[(a%2 == 0) & (a>4)]

array([6])

In [244]:
# create an array storing values from 5 to 50 and print the even numbers divisible by 5

In [246]:
a = np.arange(5, 51)

In [248]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [250]:
a[(a %2 == 0) & (a %5 ==0)]

array([10, 20, 30, 40, 50])

In [252]:
a = np.arange(5, 51)

In [260]:
a[(a % 2 ==0) | (a % 3 ==0)]

array([ 6,  8,  9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24, 26, 27, 28, 30,
       32, 33, 34, 36, 38, 39, 40, 42, 44, 45, 46, 48, 50])