In [1]:
import numpy as np

In [3]:
a = np.arange(20)

In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
new = a.reshape(5,4)

In [9]:
new

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
new = a.reshape(10,2)

In [15]:
new

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [17]:
arr = np.array([3,2,0,1])

In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
for item in a:
    print(item)

[1 2 3]
[4 5 6]
[7 8 9]


In [25]:
for item in a:
    for val in item :
        print(val)

1
2
3
4
5
6
7
8
9


In [27]:
for item in np.nditer(a):
    print(item)

1
2
3
4
5
6
7
8
9
