In [2]:
import numpy as np

In [12]:
import pandas as pd

In [10]:
a = np.array([1,2,3,4])

In [12]:
a

array([1, 2, 3, 4])

In [16]:
b = np.array([[1,2,3],[4,5,6]])

In [18]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b.ndim

2

In [22]:
a.ndim

1

In [24]:
a.size

4

In [26]:
b.size

6

In [28]:
a.dtype

dtype('int64')

In [30]:
b.dtype

dtype('int64')

In [32]:
a.shape

(4,)

In [34]:
b.shape

(2, 3)

In [36]:
np.empty(3)

array([3., 2., 1.])

In [38]:
np.empty(3, dtype ='int')

array([4613937818241073159, 4611686018427387884, 4607182418800017423])

In [40]:
np.empty((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [46]:
c = np.eye(3,5)

In [48]:
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [50]:
c.ndim

2

In [52]:
c.size

15

In [54]:
c.shape

(3, 5)

In [56]:
c.dtype

dtype('float64')

In [60]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [64]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [68]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [72]:
np.full(5,8)

array([8, 8, 8, 8, 8])

In [74]:
np.full((2,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [8]:
a = np.full((2,5,9,3),4)

In [76]:
d = np.array([1,2,3,4,5,6,7])

In [18]:
a = np.full((2,3),6)

In [20]:
a

array([[6, 6, 6],
       [6, 6, 6]])

In [22]:
pd.Series(a)

ValueError: Data must be 1-dimensional, got ndarray of shape (2, 3) instead

In [78]:
d

array([1, 2, 3, 4, 5, 6, 7])

In [80]:
d.dtype

dtype('int64')

In [90]:
d.sum

<function ndarray.sum>

In [92]:
d.sum()

28

In [94]:
d.max()

7

In [96]:
d.min()

1

In [98]:
d.mean()

4.0

In [100]:
d.var()

4.0

In [102]:
d.std()

2.0