In [2]:
import numpy as np

In [8]:
a = np.array([1,2,3,4])

In [10]:
a

array([1, 2, 3, 4])

In [16]:
b = np.array([1,2,3.00])

In [18]:
b

array([1., 2., 3.])

In [24]:
c = np.array([1.0,2.0,3.0], dtype = 'int')

In [26]:
c

array([1, 2, 3])

In [28]:
d = np.array([1.9,2,3.0], dtype = 'int')

In [30]:
d

array([1, 2, 3])